=== Nocitech/CPAR/CPAR.UnitTests/Schemas/experiment.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="experiment" nillable="true" type="Experiment" />
  <xs:complexType name="Experiment">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="description" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="experimenters" type="ArrayOfExperimenter" />
      <xs:element minOccurs="0" maxOccurs="1" name="factors" type="ArrayOfFactor" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="protocol" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ArrayOfExperimenter">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="experimenter" nillable="true" type="Experimenter" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Experimenter">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="title" type="xs:string" />
    <xs:attribute name="affiliation" type="xs:string" />
    <xs:attribute name="mail" type="xs:string" />
    <xs:attribute name="phone" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ArrayOfFactor">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="factor" nillable="true" type="Factor" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Factor">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="level" type="Level" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="type" type="FactorType" use="required" />
  </xs:complexType>
  <xs:complexType name="Level">
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="FactorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="between-subjects" />
      <xs:enumeration value="within-subjects" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Nocitech/CPAR/CPAR.UnitTests/Schemas/sample-experiment.xml
<?xml version="1.0" encoding="UTF-8"?>
<experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="c:\cpar\xsd\experiment.xsd"
            name="Sample Experiment" 
            protocol="sample-protocol">
  
<description>
This is a test experiment that is created in order to be used during development of the CPAR Software.
</description>
  
<experimenters>
  <experimenter name="Kristian Hennings" affiliation="AAU" title="Adjunct Ass. Professor" mail="krhe@hst.aau.dk" phone="20725669"/>
  <experimenter name="Laura Petrini" affiliation="AAU" title="Adjunct Ass. Professor" mail="lap@hst.aau.dk" phone="20725669"/>
</experimenters>
  
<factors>
  <factor name="Group" type="multiple-exclusive">
    <level name="A"/>
    <level name="B"/>
  </factor>  
  <factor name="Session" type="free">
    <level name="Pre-stimulus"/>
    <level name="Post-stimulus"/>
  </factor>
</factors>
  
</experiment>
